import { z } from "zod"

export const BayaranSchema = z.object({
  id: z.string().optional(), // ID is generated by the backend for new records
  daripada: z.string().min(1, "Daripada diperlukan"),
  tarikhTerima: z.string().min(1, "Tarikh Terima diperlukan"),
  perkara: z.string().min(1, "Perkara diperlukan"),
  nilaiBayaran: z.string().optional(),
  bayaranKe: z.string().optional(),
  kategori: z.string().optional(),
  noKontrak: z.string().optional(),
  tarikhMemoLadang: z.string().optional(),
  statusLadang: z.string().optional(),
  tarikhHantar: z.string().optional(),
  tarikhPpnP: z.string().optional(),
  tarikhPn: z.string().optional(),
  penerima: z.string().optional(),
  statusBayaran: z.string().optional(),
  tarikhBayar: z.string().optional(),
  nomborBaucer: z.string().optional(),
  notaKaki: z.string().optional(),
})

export const BulkUpdateBayaranSchema = z.object({
  ids: z.array(z.string()).min(1, "Sekurang-kurangnya satu ID diperlukan"),
  newStatus: z.string().min(1, "Status baru diperlukan"),
  user: z.string().optional(),
})
